version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers

    steps:
      - checkout
      - run: sudo apt update
      - run: sudo composer self-update
      - run: sudo docker-php-ext-install zip

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      # - run: composer install -n --optimize-autoloader --classmap-authoritative
      - run: composer dump-autoload --optimize --classmap-authoritative
      - save_cache:
          key: composer-v1-({ checksum "composer.json" })
          paths:
              - vendor
      - run:
          name: "Create Environment file"
          command: mv .env.test .env

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: Run web server
          command: php -S localhost:8000 -t public
          background: true

workflows:
    version: 2
    unit_test:
        jobs:
            - phpunit